//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 28. 4. 2012 15:43:10
namespace SharedProxy.MainServerService
{
    
    /// <summary>
    /// There are no comments for ProxyServiceContextEntities in the schema.
    /// </summary>
    public partial class ProxyServiceContextEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ProxyServiceContextEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ProxyServiceContextEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("SharedProxy.Streams.Output", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("SharedProxy.MainServerService", typeName.Substring(26)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("SharedProxy.MainServerService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("SharedProxy.Streams.Output.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for ProxyServiceItems in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ServiceItem> ProxyServiceItems
        {
            get
            {
                if ((this._ProxyServiceItems == null))
                {
                    this._ProxyServiceItems = base.CreateQuery<ServiceItem>("ProxyServiceItems");
                }
                return this._ProxyServiceItems;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ServiceItem> _ProxyServiceItems;
        /// <summary>
        /// There are no comments for ProxyServiceItems in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProxyServiceItems(ServiceItem serviceItem)
        {
            base.AddObject("ProxyServiceItems", serviceItem);
        }
    }
    /// <summary>
    /// There are no comments for SharedProxy.Streams.Output.ServiceItem in the schema.
    /// </summary>
    /// <KeyProperties>
    /// NoCacheItemId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ProxyServiceItems")]
    [global::System.Data.Services.Common.HasStreamAttribute()]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("NoCacheItemId")]
    public partial class ServiceItem : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ServiceItem object.
        /// </summary>
        /// <param name="noCacheItemId">Initial value of NoCacheItemId.</param>
        /// <param name="statusCode">Initial value of StatusCode.</param>
        /// <param name="downloadMethod">Initial value of DownloadMethod.</param>
        /// <param name="dateModified">Initial value of DateModified.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ServiceItem CreateServiceItem(int noCacheItemId, int statusCode, int downloadMethod, global::System.DateTime dateModified)
        {
            ServiceItem serviceItem = new ServiceItem();
            serviceItem.NoCacheItemId = noCacheItemId;
            serviceItem.StatusCode = statusCode;
            serviceItem.DownloadMethod = downloadMethod;
            serviceItem.DateModified = dateModified;
            return serviceItem;
        }
        /// <summary>
        /// There are no comments for Property NoCacheItemId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int NoCacheItemId
        {
            get
            {
                return this._NoCacheItemId;
            }
            set
            {
                this.OnNoCacheItemIdChanging(value);
                this._NoCacheItemId = value;
                this.OnNoCacheItemIdChanged();
                this.OnPropertyChanged("NoCacheItemId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _NoCacheItemId;
        partial void OnNoCacheItemIdChanging(int value);
        partial void OnNoCacheItemIdChanged();
        /// <summary>
        /// There are no comments for Property AbsoluteUri in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string AbsoluteUri
        {
            get
            {
                return this._AbsoluteUri;
            }
            set
            {
                this.OnAbsoluteUriChanging(value);
                this._AbsoluteUri = value;
                this.OnAbsoluteUriChanged();
                this.OnPropertyChanged("AbsoluteUri");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _AbsoluteUri;
        partial void OnAbsoluteUriChanging(string value);
        partial void OnAbsoluteUriChanged();
        /// <summary>
        /// There are no comments for Property ResponseHeaders in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ResponseHeaders
        {
            get
            {
                return this._ResponseHeaders;
            }
            set
            {
                this.OnResponseHeadersChanging(value);
                this._ResponseHeaders = value;
                this.OnResponseHeadersChanged();
                this.OnPropertyChanged("ResponseHeaders");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ResponseHeaders;
        partial void OnResponseHeadersChanging(string value);
        partial void OnResponseHeadersChanged();
        /// <summary>
        /// There are no comments for Property Expires in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> Expires
        {
            get
            {
                return this._Expires;
            }
            set
            {
                this.OnExpiresChanging(value);
                this._Expires = value;
                this.OnExpiresChanged();
                this.OnPropertyChanged("Expires");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _Expires;
        partial void OnExpiresChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnExpiresChanged();
        /// <summary>
        /// There are no comments for Property StatusCode in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int StatusCode
        {
            get
            {
                return this._StatusCode;
            }
            set
            {
                this.OnStatusCodeChanging(value);
                this._StatusCode = value;
                this.OnStatusCodeChanged();
                this.OnPropertyChanged("StatusCode");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _StatusCode;
        partial void OnStatusCodeChanging(int value);
        partial void OnStatusCodeChanged();
        /// <summary>
        /// There are no comments for Property StatusDescription in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string StatusDescription
        {
            get
            {
                return this._StatusDescription;
            }
            set
            {
                this.OnStatusDescriptionChanging(value);
                this._StatusDescription = value;
                this.OnStatusDescriptionChanged();
                this.OnPropertyChanged("StatusDescription");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _StatusDescription;
        partial void OnStatusDescriptionChanging(string value);
        partial void OnStatusDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ContentType in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ContentType
        {
            get
            {
                return this._ContentType;
            }
            set
            {
                this.OnContentTypeChanging(value);
                this._ContentType = value;
                this.OnContentTypeChanged();
                this.OnPropertyChanged("ContentType");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ContentType;
        partial void OnContentTypeChanging(string value);
        partial void OnContentTypeChanged();
        /// <summary>
        /// There are no comments for Property CharacterSet in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CharacterSet
        {
            get
            {
                return this._CharacterSet;
            }
            set
            {
                this.OnCharacterSetChanging(value);
                this._CharacterSet = value;
                this.OnCharacterSetChanged();
                this.OnPropertyChanged("CharacterSet");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CharacterSet;
        partial void OnCharacterSetChanging(string value);
        partial void OnCharacterSetChanged();
        /// <summary>
        /// There are no comments for Property DownloadMethod in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DownloadMethod
        {
            get
            {
                return this._DownloadMethod;
            }
            set
            {
                this.OnDownloadMethodChanging(value);
                this._DownloadMethod = value;
                this.OnDownloadMethodChanged();
                this.OnPropertyChanged("DownloadMethod");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DownloadMethod;
        partial void OnDownloadMethodChanging(int value);
        partial void OnDownloadMethodChanged();
        /// <summary>
        /// There are no comments for Property DateModified in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this.OnDateModifiedChanging(value);
                this._DateModified = value;
                this.OnDateModifiedChanged();
                this.OnPropertyChanged("DateModified");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _DateModified;
        partial void OnDateModifiedChanging(global::System.DateTime value);
        partial void OnDateModifiedChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
