// <auto-generated />
namespace CentralServiceCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ChangeClientIdTypeRenameSyncId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeClientIdTypeRenameSyncId));
        
        string IMigrationMetadata.Id
        {
            get { return "201303081430215_ChangeClientIdTypeRenameSyncId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
