// <auto-generated />
namespace CentralServiceCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class WebObjectsAccessLogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WebObjectsAccessLogs));
        
        string IMigrationMetadata.Id
        {
            get { return "201303091258454_WebObjectsAccessLogs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
