// <auto-generated />
namespace CentralServiceCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddUidToClientCaches : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUidToClientCaches));
        
        string IMigrationMetadata.Id
        {
            get { return "201303101714340_AddUidToClientCaches"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
