// <auto-generated />
namespace CentralServiceCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class WebObjectIsTracked : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WebObjectIsTracked));
        
        string IMigrationMetadata.Id
        {
            get { return "201303091752140_WebObjectIsTracked"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
