// <auto-generated />
namespace CentralServiceCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SyncJournalItemSyncWithType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SyncJournalItemSyncWithType));
        
        string IMigrationMetadata.Id
        {
            get { return "201303100025057_SyncJournalItemSyncWithType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
