//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceCore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLog
    {
        public int Id { get; set; }
        public System.DateTime AccessedAt { get; set; }

        public virtual WebObject WebObject { get; set; }
        public virtual Workspace Workspace { get; set; }
    }
}
