//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceCore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int Id { get; set; }
        public string AbsoluteUri { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Action { get; set; }
        public int Type { get; set; }
        public string UserFirstname { get; set; }
        public string UserSurname { get; set; }
        public int ServerId { get; set; }
    
        public virtual Workspace Server { get; set; }
    }
}
