//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceCore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Recommendations = new HashSet<Recommendation>();
            this.GroupServers = new HashSet<GroupServer>();
            this.Tags = new HashSet<Tag>();
            this.UserGroups = new HashSet<UserGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual ICollection<Recommendation> Recommendations { get; set; }
        public virtual ICollection<GroupServer> GroupServers { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<UserGroup> UserGroups { get; set; }
    }
}
