//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceCore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecommendedUpdate
    {
        public RecommendedUpdate()
        {
            this.Sent = false;
            this.Priority = 10;
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Sent { get; set; }
        public int Priority { get; set; }
    
        public virtual Workspace Server { get; set; }
        public virtual WebObject Cache { get; set; }
    }
}
