//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceCore
{
    using CentralServiceCore.Data;
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        public Server()
        {
            this.Caches = new HashSet<WebObject>();
            this.ActivityLogs = new HashSet<ActivityLog>();
            this.RecommendedUpdates = new HashSet<RecommendedUpdate>();
            this.GroupServers = new HashSet<GroupServer>();
            this.Recommendations = new HashSet<Recommendation>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ServerName { get; set; }
    
        public virtual ICollection<WebObject> Caches { get; set; }
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
        public virtual ICollection<RecommendedUpdate> RecommendedUpdates { get; set; }
        public virtual ICollection<GroupServer> GroupServers { get; set; }
        public virtual ICollection<Recommendation> Recommendations { get; set; }
        public virtual Prediction Prediction { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
