//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceCore.Data
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class WebObject
    {
        public WebObject()
        {
            this.AccessLogs = new HashSet<AccessLog>();
            this.RecommendedUpdates = new HashSet<RecommendedUpdate>();
            this.PreviousUpdates = new HashSet<PreviousUpdate>();
            this.ClientCaches = new HashSet<ClientCache>();
        }

        public int Id { get; set; }
        public long CacheId { get; set; }
        public string AbsoluteUri { get; set; }
        public bool IsTracked { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual ICollection<AccessLog> AccessLogs { get; set; }
        public virtual ICollection<RecommendedUpdate> RecommendedUpdates { get; set; }
        public virtual ICollection<PreviousUpdate> PreviousUpdates { get; set; }
        public virtual ICollection<ClientCache> ClientCaches { get; set; }
    }
}
