//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralServiceCore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workspace
    {
        public Workspace()
        {
            this.Caches = new HashSet<WebObject>();
            this.ActivityLogs = new HashSet<ActivityLog>();
            this.RecommendedUpdates = new HashSet<RecommendedUpdate>();
            this.GroupServers = new HashSet<GroupServer>();
            this.Recommendations = new HashSet<Recommendation>();
            this.Users = new HashSet<User>();
            this.SyncJournalItems = new HashSet<SyncJournalItem>();
            this.SyncJournalStates = new HashSet<SyncJournalState>();
            this.ClientCaches = new HashSet<ClientCache>();
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Name { get; set; }
        public string WorkspaceId { get; set; }
    
        public virtual ICollection<WebObject> Caches { get; set; }
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
        public virtual ICollection<RecommendedUpdate> RecommendedUpdates { get; set; }
        public virtual ICollection<GroupServer> GroupServers { get; set; }
        public virtual ICollection<Recommendation> Recommendations { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<SyncJournalItem> SyncJournalItems { get; set; }
        public virtual ICollection<SyncJournalState> SyncJournalStates { get; set; }
        public virtual ICollection<ClientCache> ClientCaches { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
