//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace PhoneApp.PhoneAppCentralService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticatedUser", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v3")]
    public partial class AuthenticatedUser : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CookieField;
        
        private string ServerUsernameField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cookie {
            get {
                return this.CookieField;
            }
            set {
                if ((object.ReferenceEquals(this.CookieField, value) != true)) {
                    this.CookieField = value;
                    this.RaisePropertyChanged("Cookie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerUsername {
            get {
                return this.ServerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerUsernameField, value) != true)) {
                    this.ServerUsernameField = value;
                    this.RaisePropertyChanged("ServerUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupReport", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v2")]
    public partial class GroupReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescriptionField;
        
        private int IdField;
        
        private string NameField;
        
        private System.Collections.ObjectModel.ObservableCollection<string> TagsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<string> Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupRecommendationReport", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v2")]
    public partial class GroupRecommendationReport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AbsoluteUriField;
        
        private string DescriptionField;
        
        private int GroupIdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbsoluteUri {
            get {
                return this.AbsoluteUriField;
            }
            set {
                if ((object.ReferenceEquals(this.AbsoluteUriField, value) != true)) {
                    this.AbsoluteUriField = value;
                    this.RaisePropertyChanged("AbsoluteUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebsiteContent", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v3")]
    public partial class WebsiteContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ContentField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerInfo", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v2")]
    public partial class ServerInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string PasswordField;
        
        private string ServerNameField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerName {
            get {
                return this.ServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerNameField, value) != true)) {
                    this.ServerNameField = value;
                    this.RaisePropertyChanged("ServerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticateUserRequest", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v3")]
    public partial class AuthenticateUserRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string PasswordField;
        
        private string ServerUsernameField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerUsername {
            get {
                return this.ServerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerUsernameField, value) != true)) {
                    this.ServerUsernameField = value;
                    this.RaisePropertyChanged("ServerUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticateUserResult", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v3")]
    public partial class AuthenticateUserResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CookieField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cookie {
            get {
                return this.CookieField;
            }
            set {
                if ((object.ReferenceEquals(this.CookieField, value) != true)) {
                    this.CookieField = value;
                    this.RaisePropertyChanged("Cookie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhoneAppCentralService.IPhoneAppService")]
    public interface IPhoneAppService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneAppService/GetGroups", ReplyAction="http://tempuri.org/IPhoneAppService/GetGroupsResponse")]
        System.IAsyncResult BeginGetGroups(System.DateTime since, PhoneApp.PhoneAppCentralService.AuthenticatedUser authenticatedUser, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupReport> EndGetGroups(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneAppService/GetGroupRecommendations", ReplyAction="http://tempuri.org/IPhoneAppService/GetGroupRecommendationsResponse")]
        System.IAsyncResult BeginGetGroupRecommendations(int groupId, System.DateTime since, PhoneApp.PhoneAppCentralService.AuthenticatedUser authenticatedUser, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupRecommendationReport> EndGetGroupRecommendations(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneAppService/GetWebsiteContent", ReplyAction="http://tempuri.org/IPhoneAppService/GetWebsiteContentResponse")]
        System.IAsyncResult BeginGetWebsiteContent(string url, System.AsyncCallback callback, object asyncState);
        
        PhoneApp.PhoneAppCentralService.WebsiteContent EndGetWebsiteContent(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneAppService/GetAllServerInfos", ReplyAction="http://tempuri.org/IPhoneAppService/GetAllServerInfosResponse")]
        System.IAsyncResult BeginGetAllServerInfos(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.ServerInfo> EndGetAllServerInfos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneAppService/Authenticate", ReplyAction="http://tempuri.org/IPhoneAppService/AuthenticateResponse")]
        System.IAsyncResult BeginAuthenticate(PhoneApp.PhoneAppCentralService.AuthenticateUserRequest request, System.AsyncCallback callback, object asyncState);
        
        PhoneApp.PhoneAppCentralService.AuthenticateUserResult EndAuthenticate(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneAppServiceChannel : PhoneApp.PhoneAppCentralService.IPhoneAppService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupReport> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupReport>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetGroupRecommendationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetGroupRecommendationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupRecommendationReport> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupRecommendationReport>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWebsiteContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWebsiteContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PhoneApp.PhoneAppCentralService.WebsiteContent Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PhoneApp.PhoneAppCentralService.WebsiteContent)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAllServerInfosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAllServerInfosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.ServerInfo> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.ServerInfo>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public PhoneApp.PhoneAppCentralService.AuthenticateUserResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((PhoneApp.PhoneAppCentralService.AuthenticateUserResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneAppServiceClient : System.ServiceModel.ClientBase<PhoneApp.PhoneAppCentralService.IPhoneAppService>, PhoneApp.PhoneAppCentralService.IPhoneAppService {
        
        private BeginOperationDelegate onBeginGetGroupsDelegate;
        
        private EndOperationDelegate onEndGetGroupsDelegate;
        
        private System.Threading.SendOrPostCallback onGetGroupsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetGroupRecommendationsDelegate;
        
        private EndOperationDelegate onEndGetGroupRecommendationsDelegate;
        
        private System.Threading.SendOrPostCallback onGetGroupRecommendationsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWebsiteContentDelegate;
        
        private EndOperationDelegate onEndGetWebsiteContentDelegate;
        
        private System.Threading.SendOrPostCallback onGetWebsiteContentCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAllServerInfosDelegate;
        
        private EndOperationDelegate onEndGetAllServerInfosDelegate;
        
        private System.Threading.SendOrPostCallback onGetAllServerInfosCompletedDelegate;
        
        private BeginOperationDelegate onBeginAuthenticateDelegate;
        
        private EndOperationDelegate onEndAuthenticateDelegate;
        
        private System.Threading.SendOrPostCallback onAuthenticateCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PhoneAppServiceClient() {
        }
        
        public PhoneAppServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneAppServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneAppServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneAppServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetGroupsCompletedEventArgs> GetGroupsCompleted;
        
        public event System.EventHandler<GetGroupRecommendationsCompletedEventArgs> GetGroupRecommendationsCompleted;
        
        public event System.EventHandler<GetWebsiteContentCompletedEventArgs> GetWebsiteContentCompleted;
        
        public event System.EventHandler<GetAllServerInfosCompletedEventArgs> GetAllServerInfosCompleted;
        
        public event System.EventHandler<AuthenticateCompletedEventArgs> AuthenticateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp.PhoneAppCentralService.IPhoneAppService.BeginGetGroups(System.DateTime since, PhoneApp.PhoneAppCentralService.AuthenticatedUser authenticatedUser, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetGroups(since, authenticatedUser, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupReport> PhoneApp.PhoneAppCentralService.IPhoneAppService.EndGetGroups(System.IAsyncResult result) {
            return base.Channel.EndGetGroups(result);
        }
        
        private System.IAsyncResult OnBeginGetGroups(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.DateTime since = ((System.DateTime)(inValues[0]));
            PhoneApp.PhoneAppCentralService.AuthenticatedUser authenticatedUser = ((PhoneApp.PhoneAppCentralService.AuthenticatedUser)(inValues[1]));
            return ((PhoneApp.PhoneAppCentralService.IPhoneAppService)(this)).BeginGetGroups(since, authenticatedUser, callback, asyncState);
        }
        
        private object[] OnEndGetGroups(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupReport> retVal = ((PhoneApp.PhoneAppCentralService.IPhoneAppService)(this)).EndGetGroups(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetGroupsCompleted(object state) {
            if ((this.GetGroupsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetGroupsCompleted(this, new GetGroupsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetGroupsAsync(System.DateTime since, PhoneApp.PhoneAppCentralService.AuthenticatedUser authenticatedUser) {
            this.GetGroupsAsync(since, authenticatedUser, null);
        }
        
        public void GetGroupsAsync(System.DateTime since, PhoneApp.PhoneAppCentralService.AuthenticatedUser authenticatedUser, object userState) {
            if ((this.onBeginGetGroupsDelegate == null)) {
                this.onBeginGetGroupsDelegate = new BeginOperationDelegate(this.OnBeginGetGroups);
            }
            if ((this.onEndGetGroupsDelegate == null)) {
                this.onEndGetGroupsDelegate = new EndOperationDelegate(this.OnEndGetGroups);
            }
            if ((this.onGetGroupsCompletedDelegate == null)) {
                this.onGetGroupsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetGroupsCompleted);
            }
            base.InvokeAsync(this.onBeginGetGroupsDelegate, new object[] {
                        since,
                        authenticatedUser}, this.onEndGetGroupsDelegate, this.onGetGroupsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp.PhoneAppCentralService.IPhoneAppService.BeginGetGroupRecommendations(int groupId, System.DateTime since, PhoneApp.PhoneAppCentralService.AuthenticatedUser authenticatedUser, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetGroupRecommendations(groupId, since, authenticatedUser, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupRecommendationReport> PhoneApp.PhoneAppCentralService.IPhoneAppService.EndGetGroupRecommendations(System.IAsyncResult result) {
            return base.Channel.EndGetGroupRecommendations(result);
        }
        
        private System.IAsyncResult OnBeginGetGroupRecommendations(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int groupId = ((int)(inValues[0]));
            System.DateTime since = ((System.DateTime)(inValues[1]));
            PhoneApp.PhoneAppCentralService.AuthenticatedUser authenticatedUser = ((PhoneApp.PhoneAppCentralService.AuthenticatedUser)(inValues[2]));
            return ((PhoneApp.PhoneAppCentralService.IPhoneAppService)(this)).BeginGetGroupRecommendations(groupId, since, authenticatedUser, callback, asyncState);
        }
        
        private object[] OnEndGetGroupRecommendations(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupRecommendationReport> retVal = ((PhoneApp.PhoneAppCentralService.IPhoneAppService)(this)).EndGetGroupRecommendations(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetGroupRecommendationsCompleted(object state) {
            if ((this.GetGroupRecommendationsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetGroupRecommendationsCompleted(this, new GetGroupRecommendationsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetGroupRecommendationsAsync(int groupId, System.DateTime since, PhoneApp.PhoneAppCentralService.AuthenticatedUser authenticatedUser) {
            this.GetGroupRecommendationsAsync(groupId, since, authenticatedUser, null);
        }
        
        public void GetGroupRecommendationsAsync(int groupId, System.DateTime since, PhoneApp.PhoneAppCentralService.AuthenticatedUser authenticatedUser, object userState) {
            if ((this.onBeginGetGroupRecommendationsDelegate == null)) {
                this.onBeginGetGroupRecommendationsDelegate = new BeginOperationDelegate(this.OnBeginGetGroupRecommendations);
            }
            if ((this.onEndGetGroupRecommendationsDelegate == null)) {
                this.onEndGetGroupRecommendationsDelegate = new EndOperationDelegate(this.OnEndGetGroupRecommendations);
            }
            if ((this.onGetGroupRecommendationsCompletedDelegate == null)) {
                this.onGetGroupRecommendationsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetGroupRecommendationsCompleted);
            }
            base.InvokeAsync(this.onBeginGetGroupRecommendationsDelegate, new object[] {
                        groupId,
                        since,
                        authenticatedUser}, this.onEndGetGroupRecommendationsDelegate, this.onGetGroupRecommendationsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp.PhoneAppCentralService.IPhoneAppService.BeginGetWebsiteContent(string url, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWebsiteContent(url, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PhoneApp.PhoneAppCentralService.WebsiteContent PhoneApp.PhoneAppCentralService.IPhoneAppService.EndGetWebsiteContent(System.IAsyncResult result) {
            return base.Channel.EndGetWebsiteContent(result);
        }
        
        private System.IAsyncResult OnBeginGetWebsiteContent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string url = ((string)(inValues[0]));
            return ((PhoneApp.PhoneAppCentralService.IPhoneAppService)(this)).BeginGetWebsiteContent(url, callback, asyncState);
        }
        
        private object[] OnEndGetWebsiteContent(System.IAsyncResult result) {
            PhoneApp.PhoneAppCentralService.WebsiteContent retVal = ((PhoneApp.PhoneAppCentralService.IPhoneAppService)(this)).EndGetWebsiteContent(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWebsiteContentCompleted(object state) {
            if ((this.GetWebsiteContentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWebsiteContentCompleted(this, new GetWebsiteContentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWebsiteContentAsync(string url) {
            this.GetWebsiteContentAsync(url, null);
        }
        
        public void GetWebsiteContentAsync(string url, object userState) {
            if ((this.onBeginGetWebsiteContentDelegate == null)) {
                this.onBeginGetWebsiteContentDelegate = new BeginOperationDelegate(this.OnBeginGetWebsiteContent);
            }
            if ((this.onEndGetWebsiteContentDelegate == null)) {
                this.onEndGetWebsiteContentDelegate = new EndOperationDelegate(this.OnEndGetWebsiteContent);
            }
            if ((this.onGetWebsiteContentCompletedDelegate == null)) {
                this.onGetWebsiteContentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWebsiteContentCompleted);
            }
            base.InvokeAsync(this.onBeginGetWebsiteContentDelegate, new object[] {
                        url}, this.onEndGetWebsiteContentDelegate, this.onGetWebsiteContentCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp.PhoneAppCentralService.IPhoneAppService.BeginGetAllServerInfos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAllServerInfos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.ServerInfo> PhoneApp.PhoneAppCentralService.IPhoneAppService.EndGetAllServerInfos(System.IAsyncResult result) {
            return base.Channel.EndGetAllServerInfos(result);
        }
        
        private System.IAsyncResult OnBeginGetAllServerInfos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((PhoneApp.PhoneAppCentralService.IPhoneAppService)(this)).BeginGetAllServerInfos(callback, asyncState);
        }
        
        private object[] OnEndGetAllServerInfos(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.ServerInfo> retVal = ((PhoneApp.PhoneAppCentralService.IPhoneAppService)(this)).EndGetAllServerInfos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAllServerInfosCompleted(object state) {
            if ((this.GetAllServerInfosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAllServerInfosCompleted(this, new GetAllServerInfosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAllServerInfosAsync() {
            this.GetAllServerInfosAsync(null);
        }
        
        public void GetAllServerInfosAsync(object userState) {
            if ((this.onBeginGetAllServerInfosDelegate == null)) {
                this.onBeginGetAllServerInfosDelegate = new BeginOperationDelegate(this.OnBeginGetAllServerInfos);
            }
            if ((this.onEndGetAllServerInfosDelegate == null)) {
                this.onEndGetAllServerInfosDelegate = new EndOperationDelegate(this.OnEndGetAllServerInfos);
            }
            if ((this.onGetAllServerInfosCompletedDelegate == null)) {
                this.onGetAllServerInfosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAllServerInfosCompleted);
            }
            base.InvokeAsync(this.onBeginGetAllServerInfosDelegate, null, this.onEndGetAllServerInfosDelegate, this.onGetAllServerInfosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult PhoneApp.PhoneAppCentralService.IPhoneAppService.BeginAuthenticate(PhoneApp.PhoneAppCentralService.AuthenticateUserRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAuthenticate(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PhoneApp.PhoneAppCentralService.AuthenticateUserResult PhoneApp.PhoneAppCentralService.IPhoneAppService.EndAuthenticate(System.IAsyncResult result) {
            return base.Channel.EndAuthenticate(result);
        }
        
        private System.IAsyncResult OnBeginAuthenticate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            PhoneApp.PhoneAppCentralService.AuthenticateUserRequest request = ((PhoneApp.PhoneAppCentralService.AuthenticateUserRequest)(inValues[0]));
            return ((PhoneApp.PhoneAppCentralService.IPhoneAppService)(this)).BeginAuthenticate(request, callback, asyncState);
        }
        
        private object[] OnEndAuthenticate(System.IAsyncResult result) {
            PhoneApp.PhoneAppCentralService.AuthenticateUserResult retVal = ((PhoneApp.PhoneAppCentralService.IPhoneAppService)(this)).EndAuthenticate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAuthenticateCompleted(object state) {
            if ((this.AuthenticateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AuthenticateAsync(PhoneApp.PhoneAppCentralService.AuthenticateUserRequest request) {
            this.AuthenticateAsync(request, null);
        }
        
        public void AuthenticateAsync(PhoneApp.PhoneAppCentralService.AuthenticateUserRequest request, object userState) {
            if ((this.onBeginAuthenticateDelegate == null)) {
                this.onBeginAuthenticateDelegate = new BeginOperationDelegate(this.OnBeginAuthenticate);
            }
            if ((this.onEndAuthenticateDelegate == null)) {
                this.onEndAuthenticateDelegate = new EndOperationDelegate(this.OnEndAuthenticate);
            }
            if ((this.onAuthenticateCompletedDelegate == null)) {
                this.onAuthenticateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthenticateCompleted);
            }
            base.InvokeAsync(this.onBeginAuthenticateDelegate, new object[] {
                        request}, this.onEndAuthenticateDelegate, this.onAuthenticateCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override PhoneApp.PhoneAppCentralService.IPhoneAppService CreateChannel() {
            return new PhoneAppServiceClientChannel(this);
        }
        
        private class PhoneAppServiceClientChannel : ChannelBase<PhoneApp.PhoneAppCentralService.IPhoneAppService>, PhoneApp.PhoneAppCentralService.IPhoneAppService {
            
            public PhoneAppServiceClientChannel(System.ServiceModel.ClientBase<PhoneApp.PhoneAppCentralService.IPhoneAppService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetGroups(System.DateTime since, PhoneApp.PhoneAppCentralService.AuthenticatedUser authenticatedUser, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = since;
                _args[1] = authenticatedUser;
                System.IAsyncResult _result = base.BeginInvoke("GetGroups", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupReport> EndGetGroups(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupReport> _result = ((System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupReport>)(base.EndInvoke("GetGroups", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetGroupRecommendations(int groupId, System.DateTime since, PhoneApp.PhoneAppCentralService.AuthenticatedUser authenticatedUser, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = groupId;
                _args[1] = since;
                _args[2] = authenticatedUser;
                System.IAsyncResult _result = base.BeginInvoke("GetGroupRecommendations", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupRecommendationReport> EndGetGroupRecommendations(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupRecommendationReport> _result = ((System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.GroupRecommendationReport>)(base.EndInvoke("GetGroupRecommendations", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWebsiteContent(string url, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = url;
                System.IAsyncResult _result = base.BeginInvoke("GetWebsiteContent", _args, callback, asyncState);
                return _result;
            }
            
            public PhoneApp.PhoneAppCentralService.WebsiteContent EndGetWebsiteContent(System.IAsyncResult result) {
                object[] _args = new object[0];
                PhoneApp.PhoneAppCentralService.WebsiteContent _result = ((PhoneApp.PhoneAppCentralService.WebsiteContent)(base.EndInvoke("GetWebsiteContent", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetAllServerInfos(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAllServerInfos", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.ServerInfo> EndGetAllServerInfos(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.ServerInfo> _result = ((System.Collections.ObjectModel.ObservableCollection<PhoneApp.PhoneAppCentralService.ServerInfo>)(base.EndInvoke("GetAllServerInfos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAuthenticate(PhoneApp.PhoneAppCentralService.AuthenticateUserRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Authenticate", _args, callback, asyncState);
                return _result;
            }
            
            public PhoneApp.PhoneAppCentralService.AuthenticateUserResult EndAuthenticate(System.IAsyncResult result) {
                object[] _args = new object[0];
                PhoneApp.PhoneAppCentralService.AuthenticateUserResult _result = ((PhoneApp.PhoneAppCentralService.AuthenticateUserResult)(base.EndInvoke("Authenticate", _args, result)));
                return _result;
            }
        }
    }
}
