//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFServer.LocalServerCentralService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerInfo", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v2")]
    [System.SerializableAttribute()]
    public partial class ServerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerName {
            get {
                return this.ServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerNameField, value) != true)) {
                    this.ServerNameField = value;
                    this.RaisePropertyChanged("ServerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Updates", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v2")]
    [System.SerializableAttribute()]
    public partial class Updates : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFServer.LocalServerCentralService.LinkToUpdate[] LinksToUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFServer.LocalServerCentralService.GroupReport[] ModifiedGroupLogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFServer.LocalServerCentralService.GroupRecommendationReport[] NewGroupRecommendationLogsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFServer.LocalServerCentralService.LinkToUpdate[] LinksToUpdate {
            get {
                return this.LinksToUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.LinksToUpdateField, value) != true)) {
                    this.LinksToUpdateField = value;
                    this.RaisePropertyChanged("LinksToUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFServer.LocalServerCentralService.GroupReport[] ModifiedGroupLogs {
            get {
                return this.ModifiedGroupLogsField;
            }
            set {
                if ((object.ReferenceEquals(this.ModifiedGroupLogsField, value) != true)) {
                    this.ModifiedGroupLogsField = value;
                    this.RaisePropertyChanged("ModifiedGroupLogs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFServer.LocalServerCentralService.GroupRecommendationReport[] NewGroupRecommendationLogs {
            get {
                return this.NewGroupRecommendationLogsField;
            }
            set {
                if ((object.ReferenceEquals(this.NewGroupRecommendationLogsField, value) != true)) {
                    this.NewGroupRecommendationLogsField = value;
                    this.RaisePropertyChanged("NewGroupRecommendationLogs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkToUpdate", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v2")]
    [System.SerializableAttribute()]
    public partial class LinkToUpdate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbsoluteUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbsoluteUri {
            get {
                return this.AbsoluteUriField;
            }
            set {
                if ((object.ReferenceEquals(this.AbsoluteUriField, value) != true)) {
                    this.AbsoluteUriField = value;
                    this.RaisePropertyChanged("AbsoluteUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupReport", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v2")]
    [System.SerializableAttribute()]
    public partial class GroupReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] TagsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Tags {
            get {
                return this.TagsField;
            }
            set {
                if ((object.ReferenceEquals(this.TagsField, value) != true)) {
                    this.TagsField = value;
                    this.RaisePropertyChanged("Tags");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupRecommendationReport", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v2")]
    [System.SerializableAttribute()]
    public partial class GroupRecommendationReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbsoluteUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbsoluteUri {
            get {
                return this.AbsoluteUriField;
            }
            set {
                if ((object.ReferenceEquals(this.AbsoluteUriField, value) != true)) {
                    this.AbsoluteUriField = value;
                    this.RaisePropertyChanged("AbsoluteUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportLog", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v3")]
    [System.SerializableAttribute()]
    public partial class ReportLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFServer.LocalServerCentralService.AccessLogReport[] AccessLogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFServer.LocalServerCentralService.ActivityLogReport[] ActivityLogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFServer.LocalServerCentralService.GroupReport[] GroupLogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFServer.LocalServerCentralService.GroupRecommendationReport[] GroupRecommendationLogsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFServer.LocalServerCentralService.UserGroupReport[] UserGroupReportsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFServer.LocalServerCentralService.UserReport[] UserLogsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFServer.LocalServerCentralService.AccessLogReport[] AccessLogs {
            get {
                return this.AccessLogsField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessLogsField, value) != true)) {
                    this.AccessLogsField = value;
                    this.RaisePropertyChanged("AccessLogs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFServer.LocalServerCentralService.ActivityLogReport[] ActivityLogs {
            get {
                return this.ActivityLogsField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityLogsField, value) != true)) {
                    this.ActivityLogsField = value;
                    this.RaisePropertyChanged("ActivityLogs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFServer.LocalServerCentralService.GroupReport[] GroupLogs {
            get {
                return this.GroupLogsField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupLogsField, value) != true)) {
                    this.GroupLogsField = value;
                    this.RaisePropertyChanged("GroupLogs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFServer.LocalServerCentralService.GroupRecommendationReport[] GroupRecommendationLogs {
            get {
                return this.GroupRecommendationLogsField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupRecommendationLogsField, value) != true)) {
                    this.GroupRecommendationLogsField = value;
                    this.RaisePropertyChanged("GroupRecommendationLogs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFServer.LocalServerCentralService.UserGroupReport[] UserGroupReports {
            get {
                return this.UserGroupReportsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserGroupReportsField, value) != true)) {
                    this.UserGroupReportsField = value;
                    this.RaisePropertyChanged("UserGroupReports");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFServer.LocalServerCentralService.UserReport[] UserLogs {
            get {
                return this.UserLogsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLogsField, value) != true)) {
                    this.UserLogsField = value;
                    this.RaisePropertyChanged("UserLogs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccessLogReport", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v2")]
    [System.SerializableAttribute()]
    public partial class AccessLogReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbsoluteUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AccessedAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DownloadedFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FetchDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbsoluteUri {
            get {
                return this.AbsoluteUriField;
            }
            set {
                if ((object.ReferenceEquals(this.AbsoluteUriField, value) != true)) {
                    this.AbsoluteUriField = value;
                    this.RaisePropertyChanged("AbsoluteUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AccessedAt {
            get {
                return this.AccessedAtField;
            }
            set {
                if ((this.AccessedAtField.Equals(value) != true)) {
                    this.AccessedAtField = value;
                    this.RaisePropertyChanged("AccessedAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DownloadedFrom {
            get {
                return this.DownloadedFromField;
            }
            set {
                if ((this.DownloadedFromField.Equals(value) != true)) {
                    this.DownloadedFromField = value;
                    this.RaisePropertyChanged("DownloadedFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FetchDuration {
            get {
                return this.FetchDurationField;
            }
            set {
                if ((this.FetchDurationField.Equals(value) != true)) {
                    this.FetchDurationField = value;
                    this.RaisePropertyChanged("FetchDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityLogReport", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v2")]
    [System.SerializableAttribute()]
    public partial class ActivityLogReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbsoluteURIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFServer.LocalServerCentralService.ActivityAction ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFServer.LocalServerCentralService.ActivityType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserFirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserSurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbsoluteURI {
            get {
                return this.AbsoluteURIField;
            }
            set {
                if ((object.ReferenceEquals(this.AbsoluteURIField, value) != true)) {
                    this.AbsoluteURIField = value;
                    this.RaisePropertyChanged("AbsoluteURI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFServer.LocalServerCentralService.ActivityAction Action {
            get {
                return this.ActionField;
            }
            set {
                if ((this.ActionField.Equals(value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFServer.LocalServerCentralService.ActivityType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFirstname {
            get {
                return this.UserFirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFirstnameField, value) != true)) {
                    this.UserFirstnameField = value;
                    this.RaisePropertyChanged("UserFirstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserSurname {
            get {
                return this.UserSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSurnameField, value) != true)) {
                    this.UserSurnameField = value;
                    this.RaisePropertyChanged("UserSurname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserGroupReport", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v3")]
    [System.SerializableAttribute()]
    public partial class UserGroupReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId {
            get {
                return this.GroupIdField;
            }
            set {
                if ((this.GroupIdField.Equals(value) != true)) {
                    this.GroupIdField = value;
                    this.RaisePropertyChanged("GroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserReport", Namespace="http://schemas.datacontract.org/2004/07/ServiceEntities.CentralService.v3")]
    [System.SerializableAttribute()]
    public partial class UserReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordSaltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordHash {
            get {
                return this.PasswordHashField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordHashField, value) != true)) {
                    this.PasswordHashField = value;
                    this.RaisePropertyChanged("PasswordHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PasswordSalt {
            get {
                return this.PasswordSaltField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordSaltField, value) != true)) {
                    this.PasswordSaltField = value;
                    this.RaisePropertyChanged("PasswordSalt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityAction", Namespace="http://imaginecup.fiit.stuba.sk/2012/")]
    public enum ActivityAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Create = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Read = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delete = 40,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityType", Namespace="http://imaginecup.fiit.stuba.sk/2012/")]
    public enum ActivityType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Visit = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rating = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Recommend = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tag = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Share = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Register = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Search = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Group = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 100,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalServerCentralService.ILocalServerService")]
    public interface ILocalServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalServerService/Update", ReplyAction="http://tempuri.org/ILocalServerService/UpdateResponse")]
        WPFServer.LocalServerCentralService.Updates Update(System.DateTime lastUpdate, WPFServer.LocalServerCentralService.ServerInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocalServerService/Report", ReplyAction="http://tempuri.org/ILocalServerService/ReportResponse")]
        void Report(WPFServer.LocalServerCentralService.ReportLog reports, WPFServer.LocalServerCentralService.ServerInfo info);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocalServerServiceChannel : WPFServer.LocalServerCentralService.ILocalServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocalServerServiceClient : System.ServiceModel.ClientBase<WPFServer.LocalServerCentralService.ILocalServerService>, WPFServer.LocalServerCentralService.ILocalServerService {
        
        public LocalServerServiceClient() {
        }
        
        public LocalServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocalServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocalServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WPFServer.LocalServerCentralService.Updates Update(System.DateTime lastUpdate, WPFServer.LocalServerCentralService.ServerInfo info) {
            return base.Channel.Update(lastUpdate, info);
        }
        
        public void Report(WPFServer.LocalServerCentralService.ReportLog reports, WPFServer.LocalServerCentralService.ServerInfo info) {
            base.Channel.Report(reports, info);
        }
    }
}
