//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DatabaseModel", "FK_CacheHeaders_Caches", "Caches", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WPFProxy.Database.Caches), "CacheHeaders", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WPFProxy.Database.CacheHeaders), true)]

#endregion

namespace WPFProxy.Database
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatabaseEntities object using the connection string found in the 'DatabaseEntities' section of the application configuration file.
        /// </summary>
        public DatabaseEntities() : base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(string connectionString) : base(connectionString, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(EntityConnection connection) : base(connection, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Blacklist> Blacklist
        {
            get
            {
                if ((_Blacklist == null))
                {
                    _Blacklist = base.CreateObjectSet<Blacklist>("Blacklist");
                }
                return _Blacklist;
            }
        }
        private ObjectSet<Blacklist> _Blacklist;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CacheUpdates> CacheUpdates
        {
            get
            {
                if ((_CacheUpdates == null))
                {
                    _CacheUpdates = base.CreateObjectSet<CacheUpdates>("CacheUpdates");
                }
                return _CacheUpdates;
            }
        }
        private ObjectSet<CacheUpdates> _CacheUpdates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CacheHeaders> CacheHeaders
        {
            get
            {
                if ((_CacheHeaders == null))
                {
                    _CacheHeaders = base.CreateObjectSet<CacheHeaders>("CacheHeaders");
                }
                return _CacheHeaders;
            }
        }
        private ObjectSet<CacheHeaders> _CacheHeaders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Caches> Caches
        {
            get
            {
                if ((_Caches == null))
                {
                    _Caches = base.CreateObjectSet<Caches>("Caches");
                }
                return _Caches;
            }
        }
        private ObjectSet<Caches> _Caches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PrefetchOrders> PrefetchOrders
        {
            get
            {
                if ((_PrefetchOrders == null))
                {
                    _PrefetchOrders = base.CreateObjectSet<PrefetchOrders>("PrefetchOrders");
                }
                return _PrefetchOrders;
            }
        }
        private ObjectSet<PrefetchOrders> _PrefetchOrders;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Blacklist EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBlacklist(Blacklist blacklist)
        {
            base.AddObject("Blacklist", blacklist);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CacheUpdates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCacheUpdates(CacheUpdates cacheUpdates)
        {
            base.AddObject("CacheUpdates", cacheUpdates);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CacheHeaders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCacheHeaders(CacheHeaders cacheHeaders)
        {
            base.AddObject("CacheHeaders", cacheHeaders);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Caches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCaches(Caches caches)
        {
            base.AddObject("Caches", caches);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PrefetchOrders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrefetchOrders(PrefetchOrders prefetchOrders)
        {
            base.AddObject("PrefetchOrders", prefetchOrders);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Blacklist")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Blacklist : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Blacklist object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Blacklist CreateBlacklist(global::System.Int32 id)
        {
            Blacklist blacklist = new Blacklist();
            blacklist.Id = id;
            return blacklist;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RegularExpression
        {
            get
            {
                return _RegularExpression;
            }
            set
            {
                OnRegularExpressionChanging(value);
                ReportPropertyChanging("RegularExpression");
                _RegularExpression = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RegularExpression");
                OnRegularExpressionChanged();
            }
        }
        private global::System.String _RegularExpression;
        partial void OnRegularExpressionChanging(global::System.String value);
        partial void OnRegularExpressionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CacheOnServer
        {
            get
            {
                return _CacheOnServer;
            }
            set
            {
                OnCacheOnServerChanging(value);
                ReportPropertyChanging("CacheOnServer");
                _CacheOnServer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CacheOnServer");
                OnCacheOnServerChanged();
            }
        }
        private Nullable<global::System.Int32> _CacheOnServer;
        partial void OnCacheOnServerChanging(Nullable<global::System.Int32> value);
        partial void OnCacheOnServerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="CacheHeaders")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CacheHeaders : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CacheHeaders object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="cacheId">Initial value of the CacheId property.</param>
        public static CacheHeaders CreateCacheHeaders(global::System.Int32 id, global::System.Int32 cacheId)
        {
            CacheHeaders cacheHeaders = new CacheHeaders();
            cacheHeaders.ID = id;
            cacheHeaders.CacheId = cacheId;
            return cacheHeaders;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Key
        {
            get
            {
                return _Key;
            }
            set
            {
                OnKeyChanging(value);
                ReportPropertyChanging("Key");
                _Key = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Key");
                OnKeyChanged();
            }
        }
        private global::System.String _Key;
        partial void OnKeyChanging(global::System.String value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CacheId
        {
            get
            {
                return _CacheId;
            }
            set
            {
                OnCacheIdChanging(value);
                ReportPropertyChanging("CacheId");
                _CacheId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CacheId");
                OnCacheIdChanged();
            }
        }
        private global::System.Int32 _CacheId;
        partial void OnCacheIdChanging(global::System.Int32 value);
        partial void OnCacheIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_CacheHeaders_Caches", "Caches")]
        public Caches Caches
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caches>("DatabaseModel.FK_CacheHeaders_Caches", "Caches").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caches>("DatabaseModel.FK_CacheHeaders_Caches", "Caches").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Caches> CachesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Caches>("DatabaseModel.FK_CacheHeaders_Caches", "Caches");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Caches>("DatabaseModel.FK_CacheHeaders_Caches", "Caches", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Caches")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Caches : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Caches object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="absoluteUri">Initial value of the AbsoluteUri property.</param>
        public static Caches CreateCaches(global::System.Int32 id, global::System.String absoluteUri)
        {
            Caches caches = new Caches();
            caches.ID = id;
            caches.AbsoluteUri = absoluteUri;
            return caches;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AbsoluteUri
        {
            get
            {
                return _AbsoluteUri;
            }
            set
            {
                OnAbsoluteUriChanging(value);
                ReportPropertyChanging("AbsoluteUri");
                _AbsoluteUri = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AbsoluteUri");
                OnAbsoluteUriChanged();
            }
        }
        private global::System.String _AbsoluteUri;
        partial void OnAbsoluteUriChanging(global::System.String value);
        partial void OnAbsoluteUriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserAgent
        {
            get
            {
                return _UserAgent;
            }
            set
            {
                OnUserAgentChanging(value);
                ReportPropertyChanging("UserAgent");
                _UserAgent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserAgent");
                OnUserAgentChanged();
            }
        }
        private global::System.String _UserAgent;
        partial void OnUserAgentChanging(global::System.String value);
        partial void OnUserAgentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Expires
        {
            get
            {
                return _Expires;
            }
            set
            {
                OnExpiresChanging(value);
                ReportPropertyChanging("Expires");
                _Expires = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Expires");
                OnExpiresChanged();
            }
        }
        private Nullable<global::System.DateTime> _Expires;
        partial void OnExpiresChanging(Nullable<global::System.DateTime> value);
        partial void OnExpiresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StatusCode
        {
            get
            {
                return _StatusCode;
            }
            set
            {
                OnStatusCodeChanging(value);
                ReportPropertyChanging("StatusCode");
                _StatusCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusCode");
                OnStatusCodeChanged();
            }
        }
        private Nullable<global::System.Int32> _StatusCode;
        partial void OnStatusCodeChanging(Nullable<global::System.Int32> value);
        partial void OnStatusCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateStored
        {
            get
            {
                return _DateStored;
            }
            set
            {
                OnDateStoredChanging(value);
                ReportPropertyChanging("DateStored");
                _DateStored = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateStored");
                OnDateStoredChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateStored;
        partial void OnDateStoredChanging(Nullable<global::System.DateTime> value);
        partial void OnDateStoredChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StatusDescription
        {
            get
            {
                return _StatusDescription;
            }
            set
            {
                OnStatusDescriptionChanging(value);
                ReportPropertyChanging("StatusDescription");
                _StatusDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StatusDescription");
                OnStatusDescriptionChanged();
            }
        }
        private global::System.String _StatusDescription;
        partial void OnStatusDescriptionChanging(global::System.String value);
        partial void OnStatusDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CharacterSet
        {
            get
            {
                return _CharacterSet;
            }
            set
            {
                OnCharacterSetChanging(value);
                ReportPropertyChanging("CharacterSet");
                _CharacterSet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CharacterSet");
                OnCharacterSetChanged();
            }
        }
        private global::System.String _CharacterSet;
        partial void OnCharacterSetChanging(global::System.String value);
        partial void OnCharacterSetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContentType
        {
            get
            {
                return _ContentType;
            }
            set
            {
                OnContentTypeChanging(value);
                ReportPropertyChanging("ContentType");
                _ContentType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContentType");
                OnContentTypeChanged();
            }
        }
        private global::System.String _ContentType;
        partial void OnContentTypeChanging(global::System.String value);
        partial void OnContentTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AccessCount
        {
            get
            {
                return _AccessCount;
            }
            set
            {
                OnAccessCountChanging(value);
                ReportPropertyChanging("AccessCount");
                _AccessCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccessCount");
                OnAccessCountChanged();
            }
        }
        private Nullable<global::System.Int32> _AccessCount;
        partial void OnAccessCountChanging(Nullable<global::System.Int32> value);
        partial void OnAccessCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> AccessValue
        {
            get
            {
                return _AccessValue;
            }
            set
            {
                OnAccessValueChanging(value);
                ReportPropertyChanging("AccessValue");
                _AccessValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccessValue");
                OnAccessValueChanged();
            }
        }
        private Nullable<global::System.Double> _AccessValue;
        partial void OnAccessValueChanging(Nullable<global::System.Double> value);
        partial void OnAccessValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateModified
        {
            get
            {
                return _DateModified;
            }
            set
            {
                OnDateModifiedChanging(value);
                ReportPropertyChanging("DateModified");
                _DateModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModified");
                OnDateModifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateModified;
        partial void OnDateModifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private Nullable<global::System.Int64> _Size;
        partial void OnSizeChanging(Nullable<global::System.Int64> value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Parts
        {
            get
            {
                return _Parts;
            }
            set
            {
                OnPartsChanging(value);
                ReportPropertyChanging("Parts");
                _Parts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Parts");
                OnPartsChanged();
            }
        }
        private Nullable<global::System.Int32> _Parts;
        partial void OnPartsChanging(Nullable<global::System.Int32> value);
        partial void OnPartsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_CacheHeaders_Caches", "CacheHeaders")]
        public EntityCollection<CacheHeaders> CacheHeaders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CacheHeaders>("DatabaseModel.FK_CacheHeaders_Caches", "CacheHeaders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CacheHeaders>("DatabaseModel.FK_CacheHeaders_Caches", "CacheHeaders", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="CacheUpdates")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CacheUpdates : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CacheUpdates object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="absoluteUri">Initial value of the AbsoluteUri property.</param>
        public static CacheUpdates CreateCacheUpdates(global::System.Int32 id, global::System.String absoluteUri)
        {
            CacheUpdates cacheUpdates = new CacheUpdates();
            cacheUpdates.ID = id;
            cacheUpdates.AbsoluteUri = absoluteUri;
            return cacheUpdates;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCreated;
        partial void OnDateCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private Nullable<global::System.Int32> _Priority;
        partial void OnPriorityChanging(Nullable<global::System.Int32> value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AbsoluteUri
        {
            get
            {
                return _AbsoluteUri;
            }
            set
            {
                OnAbsoluteUriChanging(value);
                ReportPropertyChanging("AbsoluteUri");
                _AbsoluteUri = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AbsoluteUri");
                OnAbsoluteUriChanged();
            }
        }
        private global::System.String _AbsoluteUri;
        partial void OnAbsoluteUriChanging(global::System.String value);
        partial void OnAbsoluteUriChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="PrefetchOrders")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PrefetchOrders : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PrefetchOrders object.
        /// </summary>
        /// <param name="fromTitle">Initial value of the FromTitle property.</param>
        /// <param name="fromAbsoluteUri">Initial value of the FromAbsoluteUri property.</param>
        /// <param name="toTitle">Initial value of the ToTitle property.</param>
        /// <param name="toAbsoluteUri">Initial value of the ToAbsoluteUri property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        /// <param name="enabled">Initial value of the Enabled property.</param>
        /// <param name="completed">Initial value of the Completed property.</param>
        /// <param name="priority">Initial value of the Priority property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="isScheduled">Initial value of the IsScheduled property.</param>
        /// <param name="attempts">Initial value of the Attempts property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        public static PrefetchOrders CreatePrefetchOrders(global::System.String fromTitle, global::System.String fromAbsoluteUri, global::System.String toTitle, global::System.String toAbsoluteUri, global::System.DateTime dateCreated, global::System.Boolean enabled, global::System.Boolean completed, global::System.Byte priority, global::System.Byte status, global::System.Boolean isScheduled, global::System.Byte attempts, global::System.Int32 id)
        {
            PrefetchOrders prefetchOrders = new PrefetchOrders();
            prefetchOrders.FromTitle = fromTitle;
            prefetchOrders.FromAbsoluteUri = fromAbsoluteUri;
            prefetchOrders.ToTitle = toTitle;
            prefetchOrders.ToAbsoluteUri = toAbsoluteUri;
            prefetchOrders.DateCreated = dateCreated;
            prefetchOrders.Enabled = enabled;
            prefetchOrders.Completed = completed;
            prefetchOrders.Priority = priority;
            prefetchOrders.Status = status;
            prefetchOrders.IsScheduled = isScheduled;
            prefetchOrders.Attempts = attempts;
            prefetchOrders.Id = id;
            return prefetchOrders;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FromTitle
        {
            get
            {
                return _FromTitle;
            }
            set
            {
                OnFromTitleChanging(value);
                ReportPropertyChanging("FromTitle");
                _FromTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FromTitle");
                OnFromTitleChanged();
            }
        }
        private global::System.String _FromTitle;
        partial void OnFromTitleChanging(global::System.String value);
        partial void OnFromTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FromAbsoluteUri
        {
            get
            {
                return _FromAbsoluteUri;
            }
            set
            {
                OnFromAbsoluteUriChanging(value);
                ReportPropertyChanging("FromAbsoluteUri");
                _FromAbsoluteUri = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FromAbsoluteUri");
                OnFromAbsoluteUriChanged();
            }
        }
        private global::System.String _FromAbsoluteUri;
        partial void OnFromAbsoluteUriChanging(global::System.String value);
        partial void OnFromAbsoluteUriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ToTitle
        {
            get
            {
                return _ToTitle;
            }
            set
            {
                OnToTitleChanging(value);
                ReportPropertyChanging("ToTitle");
                _ToTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ToTitle");
                OnToTitleChanged();
            }
        }
        private global::System.String _ToTitle;
        partial void OnToTitleChanging(global::System.String value);
        partial void OnToTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ToAbsoluteUri
        {
            get
            {
                return _ToAbsoluteUri;
            }
            set
            {
                OnToAbsoluteUriChanging(value);
                ReportPropertyChanging("ToAbsoluteUri");
                _ToAbsoluteUri = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ToAbsoluteUri");
                OnToAbsoluteUriChanged();
            }
        }
        private global::System.String _ToAbsoluteUri;
        partial void OnToAbsoluteUriChanging(global::System.String value);
        partial void OnToAbsoluteUriChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Enabled
        {
            get
            {
                return _Enabled;
            }
            set
            {
                OnEnabledChanging(value);
                ReportPropertyChanging("Enabled");
                _Enabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Enabled");
                OnEnabledChanged();
            }
        }
        private global::System.Boolean _Enabled;
        partial void OnEnabledChanging(global::System.Boolean value);
        partial void OnEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Completed
        {
            get
            {
                return _Completed;
            }
            set
            {
                OnCompletedChanging(value);
                ReportPropertyChanging("Completed");
                _Completed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Completed");
                OnCompletedChanged();
            }
        }
        private global::System.Boolean _Completed;
        partial void OnCompletedChanging(global::System.Boolean value);
        partial void OnCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCompleted
        {
            get
            {
                return _DateCompleted;
            }
            set
            {
                OnDateCompletedChanging(value);
                ReportPropertyChanging("DateCompleted");
                _DateCompleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCompleted");
                OnDateCompletedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCompleted;
        partial void OnDateCompletedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private global::System.Byte _Priority;
        partial void OnPriorityChanging(global::System.Byte value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Byte _Status;
        partial void OnStatusChanging(global::System.Byte value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsScheduled
        {
            get
            {
                return _IsScheduled;
            }
            set
            {
                OnIsScheduledChanging(value);
                ReportPropertyChanging("IsScheduled");
                _IsScheduled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsScheduled");
                OnIsScheduledChanged();
            }
        }
        private global::System.Boolean _IsScheduled;
        partial void OnIsScheduledChanging(global::System.Boolean value);
        partial void OnIsScheduledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Attempts
        {
            get
            {
                return _Attempts;
            }
            set
            {
                OnAttemptsChanging(value);
                ReportPropertyChanging("Attempts");
                _Attempts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Attempts");
                OnAttemptsChanged();
            }
        }
        private global::System.Byte _Attempts;
        partial void OnAttemptsChanging(global::System.Byte value);
        partial void OnAttemptsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="surname">Initial value of the Surname property.</param>
        /// <param name="current">Initial value of the Current property.</param>
        public static Users CreateUsers(global::System.Int32 id, global::System.String firstName, global::System.String surname, global::System.Int32 current)
        {
            Users users = new Users();
            users.ID = id;
            users.FirstName = firstName;
            users.Surname = surname;
            users.Current = current;
            return users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Surname
        {
            get
            {
                return _Surname;
            }
            set
            {
                OnSurnameChanging(value);
                ReportPropertyChanging("Surname");
                _Surname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Surname");
                OnSurnameChanged();
            }
        }
        private global::System.String _Surname;
        partial void OnSurnameChanging(global::System.String value);
        partial void OnSurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Mail
        {
            get
            {
                return _Mail;
            }
            set
            {
                OnMailChanging(value);
                ReportPropertyChanging("Mail");
                _Mail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Mail");
                OnMailChanged();
            }
        }
        private global::System.String _Mail;
        partial void OnMailChanging(global::System.String value);
        partial void OnMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Current
        {
            get
            {
                return _Current;
            }
            set
            {
                OnCurrentChanging(value);
                ReportPropertyChanging("Current");
                _Current = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Current");
                OnCurrentChanged();
            }
        }
        private global::System.Int32 _Current;
        partial void OnCurrentChanging(global::System.Int32 value);
        partial void OnCurrentChanged();

        #endregion
    
    }

    #endregion
    
}
